# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file_type', models.CharField(choices=[('audio', 'Audio'), ('games', 'Games'), ('videos', 'Videos'), ('applications', 'Applications'), ('books', 'Books/Docs'), ('others', 'Others')], default='others', max_length=12)),
                ('description', models.TextField(max_length=6000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
