# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20171224_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.DeleteModel(
            name='file',
        ),
    ]
