# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_auto_20180101_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.FileSegment'),
        ),
    ]
